### ISSUE TITLE
Galactic Release

### ISSUE THREAD

**Issue by DLu** [ros-controls/control_toolbox#106]
Blocked by https://github.com/ros-controls/realtime_tools/issues/74

**Comment by DLu** [comment]
No longer blocked by ros-controls/realtime_tools#74

**Comment by henningkayser** [comment]
@bmagyar tagging you since you took care about the last releases ;)
Also, could you make a release for Rolling as well to unblock our [next MoveIt release](https://github.com/ros-planning/moveit2/issues/476)?

**Comment by bmagyar** [comment]
https://github.com/ros/rosdistro/pull/29667
