### ISSUE TITLE
Integrator Windup

### ISSUE THREAD

**Issue by paulbovbel** [ros-controls/control_toolbox#34]
Even though `i_term` is clamped to `i_max`, `i_error` will continue to windup as long as there's an error. I've found this troublesome in an application with quadrotor control, where I'm trying to migrate the bespoke PID methods to the control_toolbox ones.

Would you be open to a pull adding a "antiwindup" parameter to enable clamping `i_error` by `i_max/i_gain_`?

**Comment by adolfo-rt** [comment]
Are you thinking of this as an opt-in behavior, or as an always-in addition?.

**Comment by paulbovbel** [comment]
Opt-in

**Comment by adolfo-rt** [comment]
OK, if you can prepare a pull-request we can review it. So there would be a boolean parameter for toggling the anti-windup behavior?.

**Comment by paulbovbel** [comment]
I think that would make sense, yes.

**Comment by ipa-mig** [comment]
Seeing that #52 has been merged, should this be closed?

Did you change the API of `initPid` on purpose? In the constructor you added the default argument for windup to `false`, thus keeping the old behaviour. Wouldn't it make sense to do this for the `initPid` calls the same way?

(Yeah, I know I'm about six weeks late ;-) )

**Comment by paulbovbel** [comment]
Thanks @ipa-mig, it would have made perfect sense to modify initPid the same way.

**Comment by ipa-mig** [comment]
@paulbovbel will this be done for others not stumbling upon the same? (Even though I actually appreciate having a proper antiwindup and would have probably not found this change without the build error :-) )

**Comment by paulbovbel** [comment]
I'm totally open to it, although @bmagyar would be the one to ask. Would you be able to put up a PR?
