### ISSUE TITLE
Jade Release

### ISSUE THREAD

**Issue by wjwwood** [ros-controls/control_toolbox#36]
`gazebo_ros_control` depends on this and it's part of "desktop-full", so it would be nice to have an initial version of this out as soon as possible.

Thanks in advanced.

**Comment by adolfo-rt** [comment]
I plan to do the release next Thursday April 30, 2015.

**Comment by adolfo-rt** [comment]
1.13.1 has been released into indigo https://github.com/ros/rosdistro/pull/8249
Once `realtime_tools` makes it into jade (https://github.com/ros/rosdistro/pull/8251), I'll also release 1.13.1 into jade.

**Comment by adolfo-rt** [comment]
Done
https://github.com/ros/rosdistro/pull/8252
