### ISSUE TITLE
Travis build job needs update

### ISSUE THREAD

**Issue by progtologist** [ros-controls/control_toolbox#61]
Currently all the branches in the control_toolbox still use the old configuration (without docker) that means that all building is done using hydro (even for the kinetic branch).

Although it works at the moment, we really should update it as various issues might arise and go unnoticed (all builds are tested using ubuntu 12.04 which is quite old).

I can make a PR with a fix if the maintainers agree as well.

**Comment by bmagyar** [comment]
That would be amazing, thank you!

Note: we are using industrial_ci for some stuff already, it'd be good to stick with that
