### ISSUE TITLE
New release please?

### ISSUE THREAD

**Issue by mikepurvis** [ros-controls/control_toolbox#67]
Last one was over a year ago— would be great to get another tag, and blooms for kinetic + lunar.

**Comment by bmagyar** [comment]
Absolutely Sir, I've told the chef to cook up a new release!

**Comment by mikepurvis** [comment]
Thank you sir!

**Comment by bmagyar** [comment]
Pushed one today but then spotted a few things that need touching up, may get another out this or early next week!
